# CMake generated Testfile for 
# Source directory: /home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration
# Build directory: /home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test/integration
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[parser]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_parser")
set_tests_properties([=[parser]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration/CMakeLists.txt;3;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration/CMakeLists.txt;0;")
add_test([=[v0_parser]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parser")
set_tests_properties([=[v0_parser]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration/CMakeLists.txt;4;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration/CMakeLists.txt;0;")
add_test([=[v1_parser]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v1_parser")
set_tests_properties([=[v1_parser]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration/CMakeLists.txt;5;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/integration/CMakeLists.txt;0;")
