# CMake generated Testfile for 
# Source directory: /home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0
# Build directory: /home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test/unit/v0
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[v0_parse_arrhenius]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_arrhenius")
set_tests_properties([=[v0_parse_arrhenius]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;4;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_branched]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_branched")
set_tests_properties([=[v0_parse_branched]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;5;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_emission]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_emission")
set_tests_properties([=[v0_parse_emission]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;6;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_first_order_loss]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_first_order_loss")
set_tests_properties([=[v0_parse_first_order_loss]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;7;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_photolysis]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_photolysis")
set_tests_properties([=[v0_parse_photolysis]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;8;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_surface]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_surface")
set_tests_properties([=[v0_parse_surface]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;9;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_ternary_chemical_activation]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_ternary_chemical_activation")
set_tests_properties([=[v0_parse_ternary_chemical_activation]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;10;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_troe]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_troe")
set_tests_properties([=[v0_parse_troe]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;11;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_tunneling]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_tunneling")
set_tests_properties([=[v0_parse_tunneling]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;12;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_user_defined]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_user_defined")
set_tests_properties([=[v0_parse_user_defined]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;13;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
add_test([=[v0_parse_species]=] "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test/test_v0_parse_species")
set_tests_properties([=[v0_parse_species]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/MechanismConfiguration/MechanismConfiguration/build_test" _BACKTRACE_TRIPLES "/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;34;add_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/cmake/test_util.cmake;27;add_mech_config_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;14;create_standard_test;/home/runner/work/MechanismConfiguration/MechanismConfiguration/test/unit/v0/CMakeLists.txt;0;")
