name: Mac

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:

  xcode_macos_13:
    runs-on: macos-13
    continue-on-error: true
    strategy:
      matrix:
        xcode: ['16.4']
        build_type: [Release]
        compiler:
          - { cpp: g++-13 }
          - { cpp: g++-14 }
          - { cpp: clang++ }
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      CXX: ${{ matrix.compiler.cpp }}

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure --verbose