name: Ubuntu

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        enable_json: [OFF, ON]
        enable_yaml: [OFF, ON]
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D ENABLE_JSON=${{ matrix.enable_json }} -D ENABLE_YAML=${{ matrix.enable_yaml }}

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose -j 10

  clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        enable_json: [OFF, ON]
        enable_yaml: [OFF, ON]
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D ENABLE_JSON=${{ matrix.enable_json }} -D ENABLE_YAML=${{ matrix.enable_yaml }}

      - name: Build
        run: cmake --build build --verbose

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose -j 10